name: selly_clone
description: "A Flutter-based Android application that provides online sellers in Southeast Asia with an integrated keyboard overlay and order management system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Backend & Database
  supabase_flutter: ^2.0.0

  # Ads
  google_mobile_ads: ^4.0.0

  # PDF Generation
  pdf: ^3.10.0
  printing: ^5.11.0

  # Storage & Caching
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0

  # Permissions
  permission_handler: ^11.0.0

  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  modal_bottom_sheet: ^3.0.0

  # Utilities
  intl: ^0.18.0
  uuid: ^4.0.0
  connectivity_plus: ^5.0.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  http: ^1.1.0
  dio: ^5.3.2

  # Firebase removed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
