name: Deploy Edge Functions

on:
  push:
    branches: [ main ]
    paths: 
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Link project
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase link --project-ref $SUPABASE_PROJECT_ID

    - name: Apply SQL (schema/RLS/functions)
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase db execute --file supabase/sql/01_schema.sql --project-ref $SUPABASE_PROJECT_ID
        supabase db execute --file supabase/sql/02_rls.sql --project-ref $SUPABASE_PROJECT_ID
        supabase db execute --file supabase/sql/03_functions.sql --project-ref $SUPABASE_PROJECT_ID
        supabase db execute --file supabase/sql/99_seed.sql --project-ref $SUPABASE_PROJECT_ID

    - name: Set Edge Function secrets
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        MIDTRANS_SERVER_KEY: ${{ secrets.MIDTRANS_SERVER_KEY }}
        MIDTRANS_CLIENT_KEY: ${{ secrets.MIDTRANS_CLIENT_KEY }}
        XENDIT_SECRET_KEY: ${{ secrets.XENDIT_SECRET_KEY }}
        RAJAONGKIR_API_KEY: ${{ secrets.RAJAONGKIR_API_KEY }}
      run: |
        supabase secrets set \
          SUPABASE_URL=$SUPABASE_URL \
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
          MIDTRANS_SERVER_KEY=$MIDTRANS_SERVER_KEY \
          MIDTRANS_CLIENT_KEY=$MIDTRANS_CLIENT_KEY \
          XENDIT_SECRET_KEY=$XENDIT_SECRET_KEY \
          RAJAONGKIR_API_KEY=$RAJAONGKIR_API_KEY \
          --project-ref $SUPABASE_PROJECT_ID

    - name: Deploy Edge Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase functions deploy create_payment_link --project-ref $SUPABASE_PROJECT_ID
        supabase functions deploy calc_shipping --project-ref $SUPABASE_PROJECT_ID
